services:
  alpine-base:
    image: 3n88/alpine-base-image:latest
    container_name: alpine-base
    restart: always
    user: "${PUID}:${PGID}"
    environment:
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_HOME}/alpine-base:/config
