name: Build and Push to Docker Hub
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        run: |
          docker build -t 3n8/alpine-base-image:latest .
          docker push 3n8/alpine-base-image:latest
      - name: Cleanup
        run: docker rmi 3n8/alpine-base-image:latest || true
